using DotImage;
using DotImage.Color;
using TiffImage = global::DotImage.Extended.Tiff.Tiff;
using Xunit;

namespace DotImage.Extended.Tests;

public class TiffLzwDecodeTests
{
    // A Pillow-generated 40x30 RGB TIFF with LZW compression (compression=5,
    // no predictor). Used as an end-to-end regression test for the LZW decoder,
    // including its off-by-one handling and clean-EOF behavior.
    private const string PillowRgbLzwBase64 =
        "SUkqADQTAACAACBAYAAEGAABBMAAMMgACB8AAUTAADCwAAcZgAEDkAAkfgAFEYAAsmAAGFIAA0sgAHF8AA8zAAIGwABE5AAJHkABM/gAKIUABVGAALJIABdMgAMJ8ABlSgANKwABtZAAOLgAB1fgAPMUAB9mAAQNIACFsAARN8ACNygASOsACV5AATPgACeNAEDAgBAwEAMJggCBkEAUPggDCYEAcWAgEDMEAkcggFD8EAsjAgGEwEA0pAgHFkEA8vggIGYEBE2AgJHIEBM8ggKH8EBVCggLIwEBdJAgMJkEBlPggNKUEBtWAgOLIEB1cAgPL8EB9iggQMwECFpAgRNgECNvggSOUECV1ggTPIECd8AgUTUBAYIgMGBECBMIgUMhEDB8IgOEwIgQFgIgSGYIgUHIIgWH4IgYIwIgaJgIgcKQIgeLIIggL4IgiMwIgkNgIgmOQIgoPIIgqP4IgsQoIguRgIgwSQIgyTIIg0T4Ig2UoIg4VgIg6WQIg8XAIg+X4IhAYoIhCZgIhEaQIhGbAIhIb4IhKcoIhMdYIhOeQIhQfAIhSpoBgMDICAYDICgmDM0gyA4PsIEwMgSFgMgUGYMgWHIMgYH4MgaIwMgcJgMgeKQMggLL9i+DIJDMDIJjYDIKDkDIKjyDILD+DILkKDIMEYDIMkkDINEyDINk+DIOFKDIOlYDIPFkDIPlwDIQF+DIQmKDIRGYDIRmkDISGwDISm+DITHKDITnWDIUHkDIUnwDIVLQAgDBEAoGBEAwJhEA9gumEQEhMEQFBYEQFhmEQGByEQGh+EQHCMEQHiYEQICkEQIiyEQJC+EQJjMEQKDYEQKjkEQLDyEQLj+EQMEKEQMkYEQNEkEQNkyEQOE+EQOlKEQPFYEQPlkEQQFwEQQl+EQRGKEQRmYEQSGkEQSmwEQTG+EQTnKEQUHWEQUnkEQVHwEQVgAFQCgMFQDAYFQDgmFTghUBIPhUBQTBUBYWBUBgZhUBochUBwfhUB4jBUCAmBUCIpBUCQshUCYvhUCgzBUCo2BUCw5BUC48hUDA/hUDJChUDRGBUDZJBUDhMhUDpPhUDxShUD5WBUEBZBUEJcBUERfhUEZihUEhmBUEppBUExsBUE5vhUFByhUFJ1hUFR5BUFZ8BUiwZgMAwZgPszXhmBIMhmBQPhmBYTBmBgWBmBoZhmBwchmB4fhmCAjQOJgZgkKQZgmLIZgoL4ZgqMwZgsNgZguOQZgwPM+D+GYGhCgzA2IwGYHBJAzA6JkGYHhPgzA+KUGYIBWAzBCLJeAuAZgjF+DMEgxQZglGYDMEw0gZgnGwDMFA3wZgpHK2cdYMwVjyBmCwfAMwWgAB2AcAwOzNA7ASBMHYCgMg7AWB8HYDATA7AaCwHYDgZg7AeDkHYEAfg7AiEYHYEgmA7AmFIHYFAsg7AqF8HYFgzA7AuGwHYGA5A7AyHkHYGg/g7A2IUHYHBGA7A6JIHYHhMg7A+J8HYIBSg7BCKwHYIhZA7BGLgHYJBfg7BKMUHYJhmA7BONIHYKBsA7BSN8HYKhyg7BWOsHYLB5A7BaPgHYLgABEMQEQBIDAiAKAmEQBYGQiAMA+EQBoJgiAOBYEQB4MwiAQByEQCIPwiASCMEQCYTAiAUCkEQCoWQiAWC+EQC4ZgiAYDYEQDIcgiAaDyEQDYfwiAcEKEQDojAiAeEkEQD4mQiAgE+EQEIpQiAiFYEQEYsgiAkFwEQEovwiAmGKEQE4zAiAoGkEQFI2AiAqG+EQFY5QiAsHWEQFo8giAuHwEQF4AAmAJAMEwBRmwFzRTYEwBoHwmAOBMEwB4LAmAQBmhMHITAJA/CYBMIwTAKBMCYBUKQTALBZCYBcL4TAMBmUQGwJgGg5BMA2HkJgHA/hMA6IUJgHhGBMA+JIJgIBMhMBCJ9fgpQmAjFYEwEgsgmAlFwEwEwvwmAnGKEwFAzAmApGk3MbATAVjfCYCwcoTAWjrCYC4eQTAXj4CYDAAAVQFAGCqAsBgVQGATCqA0DIVQHAfCqA8EwVQIAsCqBEGYVQJA5CqBMH4VQKBGCqBUJgVQLBSCqBcLIVQMBfCqBkMwVQNBsCqBsOQVQOB5CqB0P4VQPCFCqB8RgVQQCSCqCETIVQRCfCqCMUoVQSCsCqCUWQVQTC4CqCcX4VQUDFCqCkZgVQVDSCqCsbAVQWDfCqC0coVQXDrCqC8eQVQYD4CqDEAAXQFgGC6AwBgXQGgTC6A4DIXQHgfC6BAEwXQIgsC6BIGYXQJg5C6BQH4XQKhGC6BYJgXQLhSC6BgLIXQMhfC6BoMwXQNhsC6BwOQXQOh5C6B4P4XQPiFC6CARgXQQiSC6CITIXQRifC6CQUoXQSisC6CYWQXQTi4C6CgX4XQUjFC6CoZgXQVjSC6CwbAXQWjfC6C4coXQXjrC6DAeQXQYj4C6DIAAZgGAGDMA0BgZgHMHAfcYCAH0PgmDMBIFgZgJgzDMBQHIZgKg/DMBYIwZgLhMDMBgKSkwshmA0F8MwGwzBmA4GwMwHQ5BmA8HkMwHw/hmBAIUMwIRGMIEkGYEYmQzAkE+GYEopQzAmFYGYE4sgzAoFwGYFIv2/jFDMCsZgZgWDSDMC0bAZgXDfDMC8coZgYDrDMDEeQZgZD4fmAANwDQDBuAcAwNwDwJhuAgBkNyRw3ASBMG4CYLA3AUBmG4CoOQ3AWB+G4C4Rg3AYCYG4DIUg3AaCyG4DYXw3AcDMG4DobA3AeDkG4D4eQ3AgD+G4EIhQ3AiEYG4EYkg3AkEyG4Eonw3AmFKG4E4rA3AoFkG4FIuA3AqF+G4FYxQ3AsGYG4Fo0g3AuGwG4F43w3AwHKG4GI6w3AyHkG4GY+A3A0AAHcBwBg7gPAYHcCAEw7o1DuBID4dwJgmDuBQFgdwKgzDuBYHIdwLg/DuBgIwdwMhMDuBoKQdwNhZDuBwL4dwOhmDuB4NgdwPhyDuCAPIdwQh/DuCIQodwRiMDuCQSQdwSiZDuCYT4dwTilDuCgVgdwUiyDuCoXAdwVi/DuCwYodwWjMDuC4aQdwXjYDuDAb4dwYjlDuDIdYdwZjyDuDQfAdwagAD+A8AwfwIAMRWTwCQGQ/gT18BQEwfwKgsD+BYGYfwLg5D+AwB+U+CMD+A0CYD+A2CkD+A4CyD+A6C+D+A8DMD+A+DYD+BADkD+BCDyYoD+D+BGEKD+BIEYD+BKEkD+BMEyD+BOE+D+BQFKD+BSFYcWFkD+BWFwD+BYF+D+BaGKD+BcGYD+BeGkD+BgGwD+BiG+D+BkHKf8HWD+BoHkD+BqHwD+BsAAEQAgAMEQQcEQAkAmEQTeEQAoA+EQAqBMEQAsBYEQAuBmEQAwByEQAyB+EQA0CMEQA2CYEQA4CkEQA6CyEQA8C+EQ0oEQBADYEQBCDkEQBEDyEQBGD+EQBIEKEQBKEYEQBMEkEQBOEyEQBQE+EQBSFKEQBUFYEQBWFkEQBYFwEQBaF+EQBcGKEQBeGYEQBgGkEQBiGwEQBkG+EQBmHKEQBoHWEQBqHkEQBsHwEQBuAAEgP4EgAkAYEgAmAmEgAoAyEgAqA+EgAsBMEgAuBYEgAwBmEgAyByEgA0B+EgA2CMEgA4CYEgA6CkEgA8CyEgA+C+EgBADMEgBCDYEgBEDkEgBGDyEgBID+EgBKEKEgBMEYEgBOEkEgBQEyEgBSE+EgBUFKEgBWFYEgBYFkEgBaFwEgBcF+EgBeGKEgBgGYEgBiGkEgBkGwEgBmG+EgBoHKEgBqHWEgBsHkEgBuHwEgBwAAEyAkAMEyAmAYEyAoAmEyAqRsAsnqAvBQAwBYVWBmEyA0ByEyA2B+EyA4CMEyA6CYEyA8CkEyA+CyEyBAC+EyBCDMZADYEyBGDkEyBIDyEyBKD+EyBMEKEyBOEYEyBQEkEyBSEycuE+EyBWFKEyBYFYEyBaFkEyBcFwEyBeF+EyBgGKEyBiGYEyBkGkgUGwEyBoG+EyBqHKEyBsHWEyBuHkEyBwHwEyI4FCAmAMFCAoAYFCAqAmFCAsAyFCAuA+FCAwBMFCAyBYFCA0BmFCA2ByFCA4B+FCA6CMFCA8CYFCA+CkFCBACyFCBCC+FCBEDMFCBGDYFCBIDkFCBKDyFC/qFCBOEKFCBQEYFCBSEkFCBUEyFCBWE+FCBYFKFCBaFYFCBcFkFCBeFwFCBgF+FCBiGKFCBkGYFCBmGkFCBoGwFCBqG+FCBsHKFCBuHWFCBwHkFCByHwFCB0AAFUAoAMFUAqAYFUAsAmFUAuAyFUAwA+FUWaFUA0BYFUA2BmFUA4ByFUA6B+FUA8CMFUpkFUBACkFUBCCyFUBEC+FUBGDMFUBIDYFUBKDkFUBMDyFUBOD+FUBQEKFUBSEYFUBUEkFUBWEyFUBYE+FUBaFKFUBcFYFUBeFkFUBgFwFUBiF+FUBkGKFUBmGYFUBoGkFUBqGwFUBsG+FUBuHKFUBwHWFUByHkFUB0HwFUB2AAFkAqAMFkAsAYFkAuAmFkAwAyVuZWA0zEA3I8A4BmFkA6ByFkA8B+FkA+CMFkBACYFkBCCkZYCyFkBGC+FkBIDMFkBKDYFkBMDkFkBODyFkBQD+FkBSEKdGEYFkBWEkFlKqFkBaE+FkBcFKFkBeFYFkBgFkFkBiFwFkBkF+gsGKFkBoGYFkBqGkFkBsGwFkBuG+FkBwHKFkByHWFkB0HkkWHwFkB4AAF2AsAMF2AuAYF2AwAmF2VMF2A0A+F2A2BMF2A4BYF2A6BmF2A8ByF2A+B+F2BACMF2BCCYF2BECkF2BGCyF2BIC+F2BKDMF2BMDYF2BODkF2BQDyF2BSD+F2BUEKF2BWEYF2BYEkF2BaEyF2BcE+F2BeFKF2BgFYF2BiFkF2BkFwF2BmF+F2BoGKF2BqGYF2BsGkF2BuGwF2BwG+F2ByHKF2B0HWF2B2HkF2B4HwF2B6AAGGAuAMGGAwAYGGUoGGA0AyGGA2A+GGA4BMGGA6BYGGA8BmGGA+ByGGBAB+GGBCCMGGBECYGGBGCkGGBICyGGBKC+GG0sGGBODYGGBQDkGGBSDyGGBUD+GGBWEKGGBYEYGGBaEkGGBcEyGGBeE+GGBgFKGGBiFYGGBkFkGGBmFwGGBoF+GGBqGKGGBsGYGGBuGkGGBwGwGGByG+GGB0HKGGB2HWGGB4HkGGB6HwGGB8AAGYAwAMWGAYGYA0AmGYA2AyGYA4LAA6ksA86semGYBAByGYBCB+ZwCMGYBGCYGYBICkGYBKCyGYBMC+GYBODMGYBQDYGYBSDkdeDyGYBWD+GYBYEKGYBaEYGYBcEkGYBeEyGYBgE+GYBiFKGYBkFYhCFkGYBoFwGYBqF+GYBsGKGYBuGYGYBwGkGYByGwGYB0G+kuHKGYB4HWGYB6HkGYB8HwGYI+GoTgGoA0AYGoA2AmGoA4AyGoA6A+GoA8BMGoA+BYGoBABmGoBCByGoBEB+GoBGCMGoBICYGoBKCkGoBMCyGoBOC+GoBQDMGoBSDYGoBUDkGoBWDyGo/wGoBaEKGoBcEYGoBeEkGoBgEyGoBiE+GoBkFKGoBmFYGoBoFkGoBqFwGoBsF+GoBuGKGoBwGYGoByGkGoB0GwGoB2G+GoB4HKGoB6HWGoB8HkGoB+HwGoCAAAG6A0AMG6A2AYG6A4AmG6A6AyG6A8A+G6A+BMG6BABYG6BCBmG6BEByG6BGB+G6BICMG6BKCYG6BMCkG6BOCyG6BQC+G6BSDMG6BUDYG6BWDkG6BYDyG6BaD+G6BcEKG6BeEYG6BgEkG6BiEyG6BkE+G6BmFKG6BoFYG6BqFkG6BsFwG6BuF+G6BwGKG7gkG6B0GkG6B2GwG6B4G+G6B6HKG6B8HWG6B+HkG6CAHwG6CCAAHKA2AMHKA4AYHKA6AmHKA8AyHKA+A+HKBAWcBCsUBFF+BHbyBIB+HKBKCMHKpqHKBOCkHKBQCyHKBSC+d2DMHKBWDYHKBYDkHKBaDyHKBcD+HKBeEKHKBgEYHKBiEkHKBkEyhaE+HKBoFKHKBqFYHKBsFkHKBuFwHKBwF+HKByGKHKB0GYlGGkHKB4GwHKB6G+HKB8HKHKB+HWHKCAHkHKCCHwHKCEAAHcA4AMHcA6AYHcA8AmHcToHcBAA+HcBCBMHcBEBYHcBGBmHcBIByHcBKB+HcBMCMHcBOCYHcBQCkHcBSCyHcBUC+HcBWDMHcBYDYHcBaDkHcBcDyHcBeD+HcBgEKHcBiEYHcBkEkHdKuHcBoE+HcBqFKHcBsFYHcBuFkHcBwFwHcByF+HcB0GKHcB2GYHcB4GkHcB6GwHcB8G+HdriHcCAHWHcCCHkHcCEHwHcCGAAHsA6AMHsA8AYHsA+AmHsBAAyHsBCA+HsZ+HsBGBYHsBIBmHsBKByHsBMB+HsBOCMHsBQCYHsBSCkHsBUCyHsBWC+Hs0yHsBaDYHsBcDkHsBeDyHsBgD+HsBiEKHsBkEYHsBmEkHsBoEyHsBqE+HsBsFKHsBuFYHsBwFkHsByFwHsB0F+HsB2GKHsB4GYHsB6GkHsB8GwHsB+G+HsCAHKHsCCHWHsCEHkHsCGHwHsCIICAKAAABAwABAAAAKAAAAAEBAwABAAAAHgAAAAIBAwADAAAAshMAAAMBAwABAAAABQAAAAYBAwABAAAAAgAAABEBBAABAAAACAAAABUBAwABAAAAAwAAABYBAwABAAAAHgAAABcBBAABAAAALBMAABwBAwABAAAAAQAAAAAAAAAIAAgACAA=";

    private static byte[] PillowRgbLzwBytes()
    {
        Span<byte> buf = new byte[PillowRgbLzwBase64.Length];
        Assert.True(Convert.TryFromBase64String(PillowRgbLzwBase64, buf, out int written));
        return buf[..written].ToArray();
    }

    private static (byte r, byte g, byte b) ExpectedPixel(int x, int y)
    {
        return ((byte)(x * 255 / 40), (byte)(y * 255 / 30), (byte)(x + y));
    }

    [Fact]
    public void DecodesPillowLzwRgb()
    {
        byte[] data = PillowRgbLzwBytes();
        using var ms = new MemoryStream(data);
        IImage dst = TiffImage.Decode(ms);

        Assert.Equal(40, dst.Bounds().Dx());
        Assert.Equal(30, dst.Bounds().Dy());
        for (int y = 0; y < 30; y++)
        {
            for (int x = 0; x < 40; x++)
            {
                (uint r, uint g, uint b, uint a) = dst.At(x, y).Rgba();
                (byte er, byte eg, byte eb) = ExpectedPixel(x, y);
                Assert.Equal((uint)er, r >> 8);
                Assert.Equal((uint)eg, g >> 8);
                Assert.Equal((uint)eb, b >> 8);
                Assert.Equal(255u, a >> 8);
            }
        }
    }
}
