<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../build/base.props" />
  <Import Project="../../build/sign-assembly.props" />

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <OutputType>Library</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageLicenseExpression>BSD-3-Clause</PackageLicenseExpression>
    <IsPackable>True</IsPackable>
    <PackageId>DotImage</PackageId>
    <Description>A C# port of Go's standard library image package for .NET</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <IsTrimmable>true</IsTrimmable>
    <IsAotCompatible>true</IsAotCompatible>
    <EnableAotAnalyzer>true</EnableAotAnalyzer>
  </PropertyGroup>

  <PropertyGroup>
    <VersionPrefix>0.1.0.0</VersionPrefix>
    <Version>$(VersionPrefix)</Version>
    <FileVersion>$(VersionPrefix)</FileVersion>
    <AssemblyVersion>$(VersionPrefix)</AssemblyVersion>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="\" Link="README.md" Visible="false" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.IO.Hashing" />
    <PackageReference Include="NuGetizer">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>