using System.Text;

namespace DotImage.GenDraw;

// Ports golang.org/x/image/draw/gen.go. Given the dsTypes table below it
// generates type-specialized Scale/Transform implementations (the "fast
// paths") plus dispatch switches, into DotImage.Extended.Draw's
// ScaleLeaf.Generated.cs.
internal sealed record GenData(string DType, string SType, string Sratio, string Receiver, string Op);

public static partial class Generator
{
    // ---- Type tables (gen.go dsTypes / init) ----

    // DsTypes are the (dst, src) pairs for which scale leaves are generated.
    // The last element is the fallback pair ("Image", "image.Image").
    internal static readonly (string D, string S)[] DsTypes =
    {
        ("Rgba", "Gray"),
        ("Rgba", "Nrgba"),
        ("Rgba", "Rgba"),
        ("Rgba", "YCbCr"),
        ("Rgba", "Rgba64"),
        ("Rgba", "Image"),
        ("Rgba64", "Rgba64"),
        ("Image", "Image"),
    };

    internal static readonly string[] DTypes = { "Rgba", "Rgba64", "Image" };
    internal static readonly string[] STypes = { "Gray", "Nrgba", "Rgba", "YCbCr", "Rgba64", "Image" };
    internal static readonly string[] SubsampleRatios = { "444", "422", "420", "440" };
    internal static readonly string[] Ops = { "Over", "Src" };

    // alwaysOpaque are those image types that are always opaque. For these
    // types, Over is equivalent to the faster Src, in the absence of a source
    // mask.
    internal static readonly string[] AlwaysOpaque = { "Gray", "YCbCr" };

    internal static readonly Dictionary<string, string[]> StypesForDtype = new()
    {
        ["Rgba"] = STypes,
        ["Rgba64"] = new[] { "Rgba64" },
        ["Image"] = new[] { "Image" },
        ["anyDType"] = STypes,
    };

    internal static string DstType(GenData d) => d.DType switch
    {
        "Rgba" => "RgbaImage",
        "Rgba64" => "ITargetRgba64Image",
        "Image" => "IWritableImage",
        _ => throw new Exception($"bad dType {d.DType}"),
    };

    internal static string SrcType(GenData d) => d.SType switch
    {
        "Gray" => "GrayImage",
        "Nrgba" => "NrgbaImage",
        "Rgba" => "RgbaImage",
        "YCbCr" => "YCbCrImage",
        "Rgba64" => "IRgba64Image",
        "Image" => "IImage",
        _ => throw new Exception($"bad sType {d.SType}"),
    };

    internal static string RecvCbScale(string r) => r switch { "Nn" => "NnScale", "Abl" => "AblScale", _ => throw new Exception($"bad receiver {r}") };
    internal static string RecvCbTransform(string r) => r switch { "Nn" => "NnTransform", "Abl" => "AblTransform", _ => throw new Exception($"bad receiver {r}") };

    internal static bool IsAlwaysOpaque(string sType) => Array.IndexOf(AlwaysOpaque, sType) >= 0;

    private static string Sp(int n) => new string(' ', n);

    // pixOffset mirrors gen.go; xstride/ystride are pre-composed C# substrings.
    private static string PixOffset(string m, string x, string y, string xstride, string ystride) =>
        $"({y}-{m}.Rect.Min.Y){ystride} + ({x}-{m}.Rect.Min.X){xstride}";

    private static string COffset(string x, string y, string sratio) => sratio switch
    {
        "444" => $"( {y}    - src.Rect.Min.Y  )*src.CStride + ( {x}    - src.Rect.Min.X  )",
        "422" => $"( {y}    - src.Rect.Min.Y  )*src.CStride + (({x})/2 - src.Rect.Min.X/2)",
        "420" => $"(({y})/2 - src.Rect.Min.Y/2)*src.CStride + (({x})/2 - src.Rect.Min.X/2)",
        "440" => $"(({y})/2 - src.Rect.Min.Y/2)*src.CStride + ( {x}    - src.Rect.Min.X  )",
        _ => throw new Exception($"unsupported sratio {sratio}"),
    };

    // ---- Main entry ----

    public static string Generate()
    {
        var w = new StringBuilder();
        w.Append(
            "// generated by \"dotnet run --project eng/GenDraw\". DO NOT EDIT.\n" +
            "\n" +
            "using System;\n" +
            "using DotImage;\n" +
            "using DotImage.Color;\n" +
            "using DotImage.Draw;\n" +
            "using DotImage.Extended.Math.F64;\n" +
            "using DotMath = System.Math;\n" +
            "#nullable enable\n" +
            "\n" +
            "namespace DotImage.Extended.Draw\n" +
            "{\n" +
            Sp(4) + "internal interface ITargetRgba64Image : IRgba64Image, ISetRgba64Image\n" +
            Sp(4) + "{\n" +
            Sp(4) + "}\n" +
            "\n");

        var scaleImpl = GenScaleImpl();
        w.Append(scaleImpl);

        w.Append("\n");
        w.Append(Sp(4) + "internal sealed partial class KernelScaler\n" + Sp(4) + "{\n");
        w.Append(GenKernelScalerBody(Sp(8)));
        w.Append(Sp(4) + "}\n");
        w.Append("}\n");

        return w.ToString();
    }

    // ---- ScaleImpl partial class: NN + ABL + Kernel.Transform ----

    private static string GenScaleImpl()
    {
        var w = new StringBuilder();
        w.Append(Sp(4) + "internal static partial class ScaleImpl\n" + Sp(4) + "{\n");

        foreach (var receiver in new[] { "Nn", "Abl" })
        {
            var d = new GenData("", "", "", receiver, "");
            w.Append(GenLeaves(CodeRoot, d, true));
            w.Append("\n");
            foreach (var t in DsTypes)
            {
                foreach (var op in Ops)
                {
                    if (op == "Over" && IsAlwaysOpaque(t.S))
                    {
                        continue;
                    }
                    GenLeafPair(w, CodeScaleLeafSource(receiver), CodeTransformLeafSource(receiver), t.D, t.S, receiver, op);
                }
            }
            w.Append("\n");
        }

        // Kernel.Transform (static, on ScaleImpl).
        w.Append(GenLeaves(KernelTransformRoot, new GenData("", "", "", "", ""), false));
        w.Append("\n");
        foreach (var t in DsTypes)
        {
            foreach (var op in Ops)
            {
                if (op == "Over" && IsAlwaysOpaque(t.S))
                {
                    continue;
                }
                GenLeafPair(w, CodeKernelTransformLeafSource, null, t.D, t.S, "", op);
            }
        }

        w.Append(Sp(4) + "}\n");
        return w.ToString();
    }

    private static void GenLeafPair(StringBuilder w, string scaleSource, string? transformSource, string dType, string sType, string receiver, string op)
    {
        var d = new GenData(dType, sType, "", receiver, op);
        w.Append(GenLeaves(scaleSource, d, false));
        if (transformSource != null)
        {
            w.Append("\n");
            w.Append(GenLeaves(transformSource, d, false));
        }
        w.Append("\n");
    }

    private static string GenKernelScalerBody(string indent)
    {
        var w = new StringBuilder();
        w.Append(GenLeaves(KernelScaleRoot, new GenData("", "", "", "", ""), false));
        w.Append("\n");
        foreach (var sType in STypes)
        {
            w.Append(GenLeaves(KernelScaleXLeaf, new GenData("", sType, "", "", ""), false));
        }
        w.Append("\n");
        foreach (var dType in DTypes)
        {
            foreach (var op in Ops)
            {
                w.Append(GenLeaves(KernelScaleYLeaf, new GenData(dType, "", "", "", op), false));
            }
        }
        return w.ToString();
    }

    // ---- expn / expnLine (gen.go) ----

    private static string GenLeaves(string code, GenData d, bool blankTop)
    {
        var w = new StringBuilder();
        // Mirrors gen.go expn(): for YCbCr sources, expand once per subsample
        // ratio so that each leaf is specialized to one ratio.
        if (d.SType == "YCbCr" && d.Sratio == "")
        {
            bool first = true;
            foreach (var sratio in SubsampleRatios)
            {
                w.Append(GenLeaves(code, d with { Sratio = sratio }, blankTop && first));
                first = false;
            }
            return w.ToString();
        }
        if (blankTop)
        {
            w.Append('\n');
        }
        foreach (var line in SplitLines(code))
        {
            string e = ExpnLine(line, d);
            if (e == ";")
            {
                continue;
            }
            w.Append(e);
            w.Append('\n');
        }
        return w.ToString();
    }

    private static IEnumerable<string> SplitLines(string code) => code.Split('\n');

    private static string ExpnLine(string line, GenData d)
    {
        while (true)
        {
            int i = line.IndexOf('$');
            if (i < 0)
            {
                break;
            }
            string prefix = line[..i];
            string s = line[(i + 1)..];

            i = s.Length;
            for (int j = 0; j < s.Length; j++)
            {
                if (!char.IsLetter(s[j]))
                {
                    i = j;
                    break;
                }
            }
            string dollar = s[..i];
            string suffix = s[i..];
            string indent = prefix[..(prefix.Length - prefix.TrimStart().Length)];

            string e = ExpnDollar(prefix, dollar, suffix, d, indent);
            if (e == "")
            {
                throw new Exception($"couldn't expand \"{line}\"");
            }
            line = e;
        }
        return line;
    }

    private static (string lhs, string eqOp) SplitEq(string s)
    {
        s = s.Trim();
        var (lhs1, _) = Split(s, ":=");
        if (lhs1 != "")
        {
            return (lhs1, ":=");
        }
        var (lhs2, _) = Split(s, "+=");
        if (lhs2 != "")
        {
            return (lhs2, "+=");
        }
        return ("", "");
    }

    private static (string[]? args, string extra) SplitArgs(string s)
    {
        s = s.Trim();
        if (s == "" || s[0] != '[')
        {
            return (null, "");
        }
        s = s[1..];
        int i = s.IndexOf(']');
        if (i < 0)
        {
            return (null, "");
        }
        var args = s[..i].Split(',').Select(t => t.Trim()).ToArray();
        string extra = s[(i + 1)..];
        return (args, extra);
    }

    private static (string a, string b) Split(string s, string sep)
    {
        int i = s.IndexOf(sep);
        if (i >= 0)
        {
            return (s[..i].Trim(), s[(i + sep.Length)..].Trim());
        }
        return ("", "");
    }

    private static string RelName(string s)
    {
        int i = s.LastIndexOf('.');
        return i >= 0 ? s[(i + 1)..] : s;
    }

    private static string Argf(string[] args, string s)
    {
        if (args.Length > 9)
        {
            throw new Exception("too many args");
        }
        for (int i = 0; i < args.Length; i++)
        {
            s = s.Replace("$" + i, args[i]);
        }
        return s;
    }

    // ---- Core expansion (gen.go expnDollar) ----

    private static string ExpnDollar(string prefix, string dollar, string suffix, GenData d, string indent)
    {
        switch (dollar)
        {
            case "dType":
            case "dTypeRN":
            case "sratio":
            case "sType":
            case "sTypeRN":
            case "receiver":
            case "op":
            case "cbScale":
            case "cbTransform":
                return SimpleToken(prefix, dollar, suffix, d);

            case "switch":
                return ExpandSwitch("", "", true, suffix, d.Receiver, LeadingWsOf(prefix));
            case "switchD":
                return ExpandSwitch("", "", false, suffix, d.Receiver, LeadingWsOf(prefix));
            case "switchS":
                return ExpandSwitch("", "anyDType", false, suffix, d.Receiver, LeadingWsOf(prefix));

            case "preOuter":
                return PreOuter(d, indent);
            case "preInner":
                return PreInner(d, indent);
            case "preKernelOuter":
                return PreKernelOuter(d, indent);
            case "preKernelInner":
                return PreKernelInner(d, indent);
            case "blend":
                return Blend(d, suffix, indent);
            case "clampToAlpha":
                return ClampToAlpha(d, indent);
            case "convFtou":
                return ConvFtou(d, suffix, indent);

            case "outputu":
                return OutputU(d, suffix, indent);
            case "outputf":
                return OutputF(d, suffix, indent);
            case "srcu":
            case "srcf":
                return Src(d, dollar, prefix, suffix, indent);

            case "tweakD":
                return d.DType == "Rgba" ? indent + "d += dst.Stride;" : ";";
            case "tweakDx":
                if (d.DType == "Rgba")
                {
                    int idx = prefix.IndexOf("dx++");
                    if (idx >= 0)
                    {
                        return prefix[..idx] + "dx++, d += 4" + prefix[(idx + 4)..];
                    }
                }
                return prefix;
            case "tweakDy":
                // Not used by the C# templates (the C# scaleY loop uses an indexed
                // dy and recomputes d via tweakD), kept for parity.
                return prefix;
            case "tweakP":
                // Mirrors gen.go: for Gray/YCbCr sources the trailing alpha slot
                // of the tmp array is 1.0; the remaining Gray slots duplicate pr.
                // (The C# kernel scaleX template uses $tmpOut instead of an array
                // literal, so this is kept only for fidelity with gen.go.)
                return d.SType switch
                {
                    "Gray" => prefix.TrimStart().StartsWith("pa * ") ? "1," : "pr,",
                    "YCbCr" => prefix.TrimStart().StartsWith("pa * ") ? "1," : prefix,
                    _ => prefix,
                };
            case "tweakPr":
                return d.SType == "Gray" ? indent + "pr *= b.InvTotalWeightFFFF;" : ";";
            case "tweakVarP":
                return d.SType switch
                {
                    "Gray" => indent + "double pr = 0;",
                    "YCbCr" => indent + "double pr = 0, pg = 0, pb = 0;",
                    _ => indent + "double pr = 0, pg = 0, pb = 0, pa = 0;",
                };
            case "tmpOut":
                return TmpOut(d, indent);
        }
        return "";
    }

    private static string SimpleToken(string prefix, string dollar, string suffix, GenData d)
    {
        string v = dollar switch
        {
            "dType" => DstType(d),
            "dTypeRN" => RelName(d.DType),
            "sratio" => d.Sratio,
            "sType" => SrcType(d),
            "sTypeRN" => RelName(d.SType),
            "receiver" => d.Receiver,
            "op" => d.Op,
            "cbScale" => RecvCbScale(d.Receiver),
            "cbTransform" => RecvCbTransform(d.Receiver),
            _ => throw new Exception("bad token"),
        };
        return prefix + v + suffix;
    }

    private static string LeadingWsOf(string prefix)
    {
        int n = prefix.Length - prefix.TrimStart().Length;
        return prefix[..n];
    }

    // ---- expnSwitch (gen.go) ----

    // dstVar is the pattern variable bound by the enclosing "case <dstType> d:"
    // label (or null when dst is still the method parameter, i.e. the switch is
    // at the top level or inside the dst switch's "default:"). Go's type-switch
    // shadowing is lexical: a call emitted inside a "case" (including an inner
    // switch's "default:") still sees the case-bound dst, so the generated call
    // must pass the bound variable. Similarly, srcVar is the pattern variable
    // bound by the src switch's case label, and is null in its "default:".
    private static string ExpandSwitch(string op, string dType, bool expandBoth, string template, string receiver, string indent, string? dstVar = null)
    {
        var sb = new StringBuilder();
        if (op == "" && dType != "anyDType")
        {
            sb.Append(indent).Append("switch (op)\n");
            sb.Append(indent).Append("{\n");
            foreach (var opv in Ops)
            {
                sb.Append(indent).Append(Sp(4)).Append("case Op.").Append(opv).Append(":\n");
                sb.Append(ExpandSwitch(opv, dType, expandBoth, template, receiver, indent + Sp(8), dstVar));
                sb.Append(indent).Append(Sp(8)).Append("break;\n");
            }
            sb.Append(indent).Append("}\n");
            return sb.ToString();
        }

        bool isSrc = dType != "";
        string switchVar = isSrc ? "src" : "dst";

        sb.Append(indent).Append("switch (").Append(switchVar).Append(")\n");
        sb.Append(indent).Append("{\n");

        string fallback;
        string[] values;
        if (dType != "")
        {
            fallback = "Image";
            values = StypesForDtype[dType];
        }
        else
        {
            fallback = "Image";
            values = DTypes;
        }

        foreach (var v in values)
        {
            if (dType != "" && op == "Over" && IsAlwaysOpaque(v))
            {
                continue;
            }

            if (v == fallback)
            {
                sb.Append(indent).Append(Sp(4)).Append("default:\n");
            }
            else
            {
                string label = isSrc ? SrcType(new GenData("", v, "", "", "")) : DstType(new GenData(v, "", "", "", ""));
                sb.Append(indent).Append(Sp(4)).Append("case ").Append(label).Append(' ').Append(isSrc ? "s" : "d").Append(":\n");
            }

            if (isSrc)
            {
                if (v == "YCbCr")
                {
                    sb.Append(ExpandSwitchYCbCr(op, dType, template, receiver, indent + Sp(8), dstVar));
                }
                else
                {
                    sb.Append(SwitchCall(template, new GenData(dType, v, "", receiver, op), dstVar, v == fallback ? null : "s", indent + Sp(8)));
                }
            }
            else if (!expandBoth)
            {
                sb.Append(SwitchCall(template, new GenData(v, "", "", receiver, op), v == fallback ? null : "d", null, indent + Sp(8)));
            }
            else
            {
                sb.Append(ExpandSwitch(op, v, false, template, receiver, indent + Sp(8), v == fallback ? null : "d"));
            }
            sb.Append(indent).Append(Sp(8)).Append("break;\n");
        }

        sb.Append(indent).Append("}\n");
        return sb.ToString();
    }

    private static string ExpandSwitchYCbCr(string op, string dType, string template, string receiver, string indent, string? dstVar)
    {
        var sb = new StringBuilder();
        sb.Append(indent).Append("switch (s.SubsampleRatio)\n");
        sb.Append(indent).Append("{\n");
        sb.Append(indent).Append(Sp(4)).Append("default:\n");
        sb.Append(SwitchCall(template, new GenData(dType, "Image", "", receiver, op), dstVar, "s", indent + Sp(8)));
        sb.Append(indent).Append(Sp(8)).Append("break;\n");
        foreach (var sratio in SubsampleRatios)
        {
            sb.Append(indent).Append(Sp(4)).Append("case YCbCrSubsampleRatio.Ratio").Append(sratio).Append(":\n");
            sb.Append(SwitchCall(template, new GenData(dType, "YCbCr", sratio, receiver, op), dstVar, "s", indent + Sp(8)));
            sb.Append(indent).Append(Sp(8)).Append("break;\n");
        }
        sb.Append(indent).Append("}\n");
        return sb.ToString();
    }

    private static string SwitchCall(string template, GenData d, string? dstVar, string? srcVar, string indent)
    {
        // The call line also carries the leaf-name tokens ($dTypeRN etc.) that
        // per-case data resolve. The literal parameters dst/src are rebound to
        // the pattern variables bound in the enclosing case labels, mirroring
        // Go's lexical type-switch shadowing. "default:" labels bind no pattern
        // variable, so dstVar/srcVar are null there and the original parameter
        // identifiers (dst/src) are kept.
        string call = ExpnLine(template.TrimStart(), d);
        if (dstVar != null)
        {
            call = call.Replace("dst", dstVar);
        }
        if (srcVar != null)
        {
            call = call.Replace("src", srcVar);
        }
        return indent + call + ";\n";
    }

    // ---- Snippet producers ----

    private static string PreOuter(GenData d, string ind)
    {
        string destMaskLine = ind + "IImage? dstMask = o.DstMask;\n" + ind + "Point dmp = o.DstMaskP;\n";
        switch (d.DType)
        {
            default:
                return ";";
            case "Image":
                string s = "";
                if (d.SType is "Image" or "Rgba64")
                {
                    s = ind + "IImage? srcMask = o.SrcMask;\n" + ind + "Point smp = o.SrcMaskP;\n";
                }
                return s + destMaskLine +
                    ind + "Rgba64 dstColorRGBA64 = new Rgba64(0, 0, 0, 0);";
            case "Rgba64":
                s = "";
                if (d.SType is "Image" or "Rgba64")
                {
                    s = ind + "IImage? srcMask = o.SrcMask;\n" + ind + "Point smp = o.SrcMaskP;\n";
                }
                return s + destMaskLine +
                    ind + "Rgba64 dstColorRGBA64 = new Rgba64(0, 0, 0, 0);";
        }
    }

    private static string PreInner(GenData d, string ind)
    {
        switch (d.DType)
        {
            default:
                return ";";
            case "Rgba":
                return ind + "int d = " + PixOffset("dst", "dr.Min.X+adr.Min.X", "dr.Min.Y+dy", "*4", "*dst.Stride") + ";";
        }
    }

    private static string PreKernelOuter(GenData d, string ind)
    {
        switch (d.SType)
        {
            default:
                return ";";
            case "Image":
            case "Rgba64":
                return ind + "IImage? srcMask = o.SrcMask;\n" + ind + "Point smp = o.SrcMaskP;";
        }
    }

    private static string PreKernelInner(GenData d, string ind)
    {
        switch (d.DType)
        {
            default:
                return ";";
            case "Rgba":
                return ind + "int d = " + PixOffset("dst", "dr.Min.X+dx", "dr.Min.Y+adr.Min.Y", "*4", "*dst.Stride") + ";";
        }
    }

    private static string Blend(GenData d, string suffix, string ind)
    {
        var (args, _) = SplitArgs(suffix);
        if (args == null || args.Length != 4)
        {
            return "";
        }
        var chans = d.SType switch
        {
            "Gray" => new[] { "r" },
            "YCbCr" => new[] { "r", "g", "b" },
            _ => new[] { "r", "g", "b", "a" },
        };
        var sb = new StringBuilder();
        foreach (var c in chans)
        {
            sb.Append(ind).Append($"{args[3]}{c} = {args[0]} * {args[1]}{c} + {args[2]} * {args[3]}{c};\n");
        }
        return sb.ToString().TrimEnd('\n');
    }

    private static string ClampToAlpha(GenData d, string ind)
    {
        if (IsAlwaysOpaque(d.SType))
        {
            return ";";
        }
        return ind + "if (pr > pa) { pr = pa; }\n" +
               ind + "if (pg > pa) { pg = pa; }\n" +
               ind + "if (pb > pa) { pb = pa; }";
    }

    private static string ConvFtou(GenData d, string suffix, string ind)
    {
        var (args, _) = SplitArgs(suffix);
        if (args == null || args.Length != 2)
        {
            return "";
        }
        string p = args[0], s = args[1];
        switch (d.SType)
        {
            default:
                return ind + $"uint {p}r = (uint){s}r;\n" +
                       ind + $"uint {p}g = (uint){s}g;\n" +
                       ind + $"uint {p}b = (uint){s}b;\n" +
                       ind + $"uint {p}a = (uint){s}a;";
            case "Gray":
                return ind + $"uint {p}r = (uint){s}r;";
            case "YCbCr":
                return ind + $"uint {p}r = (uint){s}r;\n" +
                       ind + $"uint {p}g = (uint){s}g;\n" +
                       ind + $"uint {p}b = (uint){s}b;";
            case "Rgba64":
                return ind + $"Rgba64 {p} = new Rgba64((ushort){s}r, (ushort){s}g, (ushort){s}b, (ushort){s}a);";
        }
    }

    // ---- srcu / srcf (gen.go) ----

    private static string Src(GenData d, string dollar, string prefix, string suffix, string indent)
    {
        var (lhs, eqOp) = SplitEq(prefix);
        if (lhs == "")
        {
            return "";
        }
        eqOp = eqOp.Replace(":=", "=");
        var (args, extra) = SplitArgs(suffix);
        if (args == null || args.Length != 2)
        {
            return "";
        }

        string tmp = dollar == "srcf" ? "u" : "";
        string x = args[0], y = args[1];
        var buf = new StringBuilder();

        switch (d.SType)
        {
            default:
                throw new Exception($"bad sType {d.SType}");
            case "Image":
            {
                string vars = indent + $"(uint {lhs}r{tmp}, uint {lhs}g{tmp}, uint {lhs}b{tmp}, uint {lhs}a{tmp}) = src.At({x}, {y}).Rgba();";
                buf.Append(vars);
                if (d.DType == "" || d.DType is "Image" or "Rgba64")
                {
                    buf.Append('\n').Append(indent).Append("if (srcMask != null)\n");
                    buf.Append(indent).Append("{\n");
                    buf.Append(indent).Append(Sp(4)).Append($"(_, _, _, uint ma) = srcMask.At(smp.X + {x}, smp.Y + {y}).Rgba();\n");
                    foreach (var c in new[] { "r", "g", "b", "a" })
                    {
                        buf.Append(indent).Append(Sp(4)).Append($"{lhs}{c}{tmp} = {lhs}{c}{tmp} * ma / 0xffff;\n");
                    }
                    buf.Append(indent).Append("}");
                }
                break;
            }
            case "Rgba64":
                buf.Append(indent).Append($"Rgba64 {lhs}{tmp} = src.Rgba64At({x}, {y});");
                if (d.DType == "" || d.DType is "Image" or "Rgba64")
                {
                    buf.Append('\n').Append(indent).Append("if (srcMask != null)\n");
                    buf.Append(indent).Append("{\n");
                    buf.Append(indent).Append(Sp(4)).Append($"(_, _, _, uint ma) = srcMask.At(smp.X + {x}, smp.Y + {y}).Rgba();\n");
                    buf.Append(indent).Append(Sp(4)).Append($"{lhs}{tmp} = new Rgba64((ushort)((uint){lhs}{tmp}.R * ma / 0xffff), (ushort)((uint){lhs}{tmp}.G * ma / 0xffff), (ushort)((uint){lhs}{tmp}.B * ma / 0xffff), (ushort)((uint){lhs}{tmp}.A * ma / 0xffff));\n");
                    buf.Append(indent).Append("}");
                }
                break;
            case "Gray":
                buf.Append(indent).Append($"int {lhs}i = {PixOffset("src", x, y, "", "*src.Stride")};\n");
                buf.Append(indent).Append($"uint {lhs}r{tmp} = (uint)src.Pix.Span[{lhs}i] * 0x101;");
                break;
            case "Nrgba":
                buf.Append(indent).Append($"int {lhs}i = {PixOffset("src", x, y, "*4", "*src.Stride")};\n");
                buf.Append(indent).Append($"uint {lhs}a{tmp} = (uint)src.Pix.Span[{lhs}i + 3] * 0x101;\n");
                buf.Append(indent).Append($"uint {lhs}r{tmp} = (uint)src.Pix.Span[{lhs}i + 0] * {lhs}a{tmp} / 0xff;\n");
                buf.Append(indent).Append($"uint {lhs}g{tmp} = (uint)src.Pix.Span[{lhs}i + 1] * {lhs}a{tmp} / 0xff;\n");
                buf.Append(indent).Append($"uint {lhs}b{tmp} = (uint)src.Pix.Span[{lhs}i + 2] * {lhs}a{tmp} / 0xff;");
                break;
            case "Rgba":
                buf.Append(indent).Append($"int {lhs}i = {PixOffset("src", x, y, "*4", "*src.Stride")};\n");
                buf.Append(indent).Append($"uint {lhs}r{tmp} = (uint)src.Pix.Span[{lhs}i + 0] * 0x101;\n");
                buf.Append(indent).Append($"uint {lhs}g{tmp} = (uint)src.Pix.Span[{lhs}i + 1] * 0x101;\n");
                buf.Append(indent).Append($"uint {lhs}b{tmp} = (uint)src.Pix.Span[{lhs}i + 2] * 0x101;\n");
                buf.Append(indent).Append($"uint {lhs}a{tmp} = (uint)src.Pix.Span[{lhs}i + 3] * 0x101;");
                break;
            case "YCbCr":
                buf.Append(indent).Append($"int {lhs}i = {PixOffset("src", x, y, "", "*src.YStride")};\n");
                buf.Append(indent).Append($"int {lhs}j = {COffset(x, y, d.Sratio)};\n");
                buf.Append(YcbcrToRgb(lhs, tmp, indent));
                break;
        }

        if (dollar == "srcf")
        {
            string[] chans;
            switch (d.SType)
            {
                default:
                    chans = new[] { "r", "g", "b", "a" };
                    break;
                case "Gray":
                    chans = new[] { "r" };
                    break;
                case "YCbCr":
                    chans = new[] { "r", "g", "b" };
                    break;
            }
            foreach (var c in chans)
            {
                string srcExpr = d.SType == "Rgba64"
                    ? $"{lhs}{tmp}.{c.ToUpperInvariant()}"
                    : $"{lhs}{c}{tmp}";
                string decl = eqOp == "+=" ? "" : "double ";
                buf.Append('\n').Append(indent).Append($"{decl}{lhs}{c} {eqOp} (double){srcExpr}{extra};");
            }
        }

        return buf.ToString().TrimEnd('\n');
    }

    private static string YcbcrToRgb(string lhs, string tmp, string ind)
    {
        var sb = new StringBuilder();
        sb.Append('\n').Append(ind).Append("// This is an inline version of the YCbCr.Rgba() conversion.\n");
        sb.Append(ind).Append($"int {lhs}yy1 = src.Y.Span[{lhs}i] * 0x10101;\n");
        sb.Append(ind).Append($"int {lhs}cb1 = src.Cb.Span[{lhs}j] - 128;\n");
        sb.Append(ind).Append($"int {lhs}cr1 = src.Cr.Span[{lhs}j] - 128;\n");
        sb.Append(ind).Append($"int {lhs}r{tmp} = ({lhs}yy1 + 91881 * {lhs}cr1) >> 8;\n");
        sb.Append(ind).Append($"int {lhs}g{tmp} = ({lhs}yy1 - 22554 * {lhs}cb1 - 46802 * {lhs}cr1) >> 8;\n");
        sb.Append(ind).Append($"int {lhs}b{tmp} = ({lhs}yy1 + 116130 * {lhs}cb1) >> 8;\n");
        foreach (var c in new[] { "r", "g", "b" })
        {
            sb.Append(ind).Append($"if ({lhs}{c}{tmp} < 0) {{ {lhs}{c}{tmp} = 0; }} else if ({lhs}{c}{tmp} > 0xffff) {{ {lhs}{c}{tmp} = 0xffff; }}\n");
        }
        return sb.ToString().TrimEnd('\n');
    }

    // ---- outputu / outputf (gen.go) ----

    private static string OutputU(GenData d, string suffix, string ind)
    {
        var (args, _) = SplitArgs(suffix);
        if (args == null || args.Length != 3)
        {
            return "";
        }
        string x = args[0], y = args[1], p = args[2];
        string setter = d.DType == "Rgba64" ? "SetRgba64" : "Set";
        string Ind1 = ind + Sp(4);

        string MaskMult4(string var) =>
            Ind1 + $"{var}r = {var}r * ma / 0xffff;\n" +
            Ind1 + $"{var}g = {var}g * ma / 0xffff;\n" +
            Ind1 + $"{var}b = {var}b * ma / 0xffff;\n" +
            Ind1 + $"{var}a = {var}a * ma / 0xffff;\n";

        var sb = new StringBuilder();

        switch (d.Op)
        {
            default:
                throw new Exception($"bad op {d.Op}");
            case "Over":
                switch (d.DType)
                {
                    default:
                        throw new Exception($"bad dType {d.DType}");
                    case "Image":
                        sb.Append(ind).Append($"(uint qr, uint qg, uint qb, uint qa) = dst.At({x}, {y}).Rgba();\n");
                        if (true)
                        {
                            sb.Append(ind).Append("if (dstMask != null)\n").Append(ind).Append("{\n");
                            sb.Append(Ind1).Append($"(_, _, _, uint ma) = dstMask.At(dmp.X + {x}, dmp.Y + {y}).Rgba();\n");
                            sb.Append(MaskMult4(p));
                            sb.Append(ind).Append("}\n");
                        }
                        sb.Append(ind).Append($"uint {p}a1 = 0xffff - {p}a;\n");
                        sb.Append(ind).Append($"dstColorRGBA64 = new Rgba64((ushort)(qr * {p}a1 / 0xffff + {p}r), (ushort)(qg * {p}a1 / 0xffff + {p}g), (ushort)(qb * {p}a1 / 0xffff + {p}b), (ushort)(qa * {p}a1 / 0xffff + {p}a));\n");
                        sb.Append(ind).Append($"dst.{setter}({x}, {y}, dstColorRGBA64);");
                        break;
                    case "Rgba64":
                        if (d.SType == "Rgba64")
                        {
                            sb.Append(ind).Append($"Rgba64 dstAt = dst.Rgba64At({x}, {y});\n");
                            sb.Append(ind).Append("if (dstMask != null)\n").Append(ind).Append("{\n");
                            sb.Append(Ind1).Append($"(_, _, _, uint ma) = dstMask.At(dmp.X + {x}, dmp.Y + {y}).Rgba();\n");
                            sb.Append(Ind1).Append($"{p} = new Rgba64((ushort)((uint){p}.R * ma / 0xffff), (ushort)((uint){p}.G * ma / 0xffff), (ushort)((uint){p}.B * ma / 0xffff), (ushort)((uint){p}.A * ma / 0xffff));\n");
                            sb.Append(ind).Append("}\n");
                            sb.Append(ind).Append($"uint {p}a1 = 0xffffu - {p}.A;\n");
                            sb.Append(ind).Append($"dstColorRGBA64 = new Rgba64((ushort)((uint)dstAt.R * {p}a1 / 0xffff + {p}.R), (ushort)((uint)dstAt.G * {p}a1 / 0xffff + {p}.G), (ushort)((uint)dstAt.B * {p}a1 / 0xffff + {p}.B), (ushort)((uint)dstAt.A * {p}a1 / 0xffff + {p}.A));\n");
                            sb.Append(ind).Append($"dst.{setter}({x}, {y}, dstColorRGBA64);");
                        }
                        else
                        {
                            sb.Append(ind).Append($"Rgba64 dstAt = dst.Rgba64At({x}, {y});\n");
                            sb.Append(ind).Append("if (dstMask != null)\n").Append(ind).Append("{\n");
                            sb.Append(Ind1).Append($"(_, _, _, uint ma) = dstMask.At(dmp.X + {x}, dmp.Y + {y}).Rgba();\n");
                            sb.Append(MaskMult4(p));
                            sb.Append(ind).Append("}\n");
                            sb.Append(ind).Append($"uint {p}a1 = 0xffff - {p}a;\n");
                            sb.Append(ind).Append($"dstColorRGBA64 = new Rgba64((ushort)((uint)dstAt.R * {p}a1 / 0xffff + {p}r), (ushort)((uint)dstAt.G * {p}a1 / 0xffff + {p}g), (ushort)((uint)dstAt.B * {p}a1 / 0xffff + {p}b), (ushort)((uint)dstAt.A * {p}a1 / 0xffff + {p}a));\n");
                            sb.Append(ind).Append($"dst.{setter}({x}, {y}, dstColorRGBA64);");
                        }
                        break;
                    case "Rgba":
                        if (d.SType == "Rgba64")
                        {
                            sb.Append(ind).Append($"uint {p}a1 = (0xffffu - {p}.A) * 0x101u;\n");
                            for (int i = 0; i < 4; i++)
                            {
                                string ch = "RGBA"[i].ToString();
                                sb.Append(ind).Append($"dst.Pix.Span[d + {i}] = (byte)(((uint)dst.Pix.Span[d + {i}] * {p}a1 / 0xffff + {p}.{ch}) >> 8);\n");
                            }
                            sb.Length -= 1;
                        }
                        else
                        {
                            sb.Append(ind).Append($"uint {p}a1 = (0xffffu - {p}a) * 0x101u;\n");
                            for (int i = 0; i < 4; i++)
                            {
                                string ch = "rgba"[i].ToString();
                                sb.Append(ind).Append($"dst.Pix.Span[d + {i}] = (byte)(((uint)dst.Pix.Span[d + {i}] * {p}a1 / 0xffff + {p}{ch}) >> 8);\n");
                            }
                            sb.Length -= 1;
                        }
                        break;
                }
                break;

            case "Src":
                switch (d.DType)
                {
                    default:
                        throw new Exception($"bad dType {d.DType}");
                    case "Image":
                        sb.Append(ind).Append("if (dstMask != null)\n").Append(ind).Append("{\n");
                        sb.Append(Ind1).Append($"(uint qr, uint qg, uint qb, uint qa) = dst.At({x}, {y}).Rgba();\n");
                        sb.Append(Ind1).Append($"(_, _, _, uint ma) = dstMask.At(dmp.X + {x}, dmp.Y + {y}).Rgba();\n");
                        sb.Append(Ind1).Append($"{p}r = {p}r * ma / 0xffff;\n");
                        sb.Append(Ind1).Append($"{p}g = {p}g * ma / 0xffff;\n");
                        sb.Append(Ind1).Append($"{p}b = {p}b * ma / 0xffff;\n");
                        sb.Append(Ind1).Append($"{p}a = {p}a * ma / 0xffff;\n");
                        sb.Append(Ind1).Append($"uint {p}a1 = 0xffff - ma;\n");
                        sb.Append(Ind1).Append($"dstColorRGBA64 = new Rgba64((ushort)(qr * {p}a1 / 0xffff + {p}r), (ushort)(qg * {p}a1 / 0xffff + {p}g), (ushort)(qb * {p}a1 / 0xffff + {p}b), (ushort)(qa * {p}a1 / 0xffff + {p}a));\n");
                        sb.Append(Ind1).Append($"dst.{setter}({x}, {y}, dstColorRGBA64);\n");
                        sb.Append(ind).Append("}\n");
                        sb.Append(ind).Append("else\n").Append(ind).Append("{\n");
                        sb.Append(Ind1).Append($"dstColorRGBA64 = new Rgba64((ushort){p}r, (ushort){p}g, (ushort){p}b, (ushort){p}a);\n");
                        sb.Append(Ind1).Append($"dst.{setter}({x}, {y}, dstColorRGBA64);\n");
                        sb.Append(ind).Append("}\n");
                        sb.Length -= 1;
                        break;
                    case "Rgba64":
                        if (d.SType == "Rgba64")
                        {
                            sb.Append(ind).Append("if (dstMask != null)\n").Append(ind).Append("{\n");
                            sb.Append(Ind1).Append($"Rgba64 dstAt = dst.Rgba64At({x}, {y});\n");
                            sb.Append(Ind1).Append($"(_, _, _, uint ma) = dstMask.At(dmp.X + {x}, dmp.Y + {y}).Rgba();\n");
                            sb.Append(Ind1).Append($"{p} = new Rgba64((ushort)((uint){p}.R * ma / 0xffff), (ushort)((uint){p}.G * ma / 0xffff), (ushort)((uint){p}.B * ma / 0xffff), (ushort)((uint){p}.A * ma / 0xffff));\n");
                            sb.Append(Ind1).Append($"uint {p}a1 = 0xffff - ma;\n");
                            sb.Append(Ind1).Append($"dstColorRGBA64 = new Rgba64((ushort)((uint)dstAt.R * {p}a1 / 0xffff + {p}.R), (ushort)((uint)dstAt.G * {p}a1 / 0xffff + {p}.G), (ushort)((uint)dstAt.B * {p}a1 / 0xffff + {p}.B), (ushort)((uint)dstAt.A * {p}a1 / 0xffff + {p}.A));\n");
                            sb.Append(Ind1).Append($"dst.{setter}({x}, {y}, dstColorRGBA64);\n");
                            sb.Append(ind).Append("}\n");
                            sb.Append(ind).Append("else\n").Append(ind).Append("{\n");
                            sb.Append(Ind1).Append($"dst.{setter}({x}, {y}, {p});\n");
                            sb.Append(ind).Append("}\n");
                            sb.Length -= 1;
                        }
                        else
                        {
                            sb.Append(ind).Append("if (dstMask != null)\n").Append(ind).Append("{\n");
                            sb.Append(Ind1).Append($"Rgba64 dstAt = dst.Rgba64At({x}, {y});\n");
                            sb.Append(Ind1).Append($"(_, _, _, uint ma) = dstMask.At(dmp.X + {x}, dmp.Y + {y}).Rgba();\n");
                            sb.Append(Ind1).Append($"{p}r = {p}r * ma / 0xffff;\n");
                            sb.Append(Ind1).Append($"{p}g = {p}g * ma / 0xffff;\n");
                            sb.Append(Ind1).Append($"{p}b = {p}b * ma / 0xffff;\n");
                            sb.Append(Ind1).Append($"{p}a = {p}a * ma / 0xffff;\n");
                            sb.Append(Ind1).Append($"uint {p}a1 = 0xffff - ma;\n");
                            sb.Append(Ind1).Append($"dstColorRGBA64 = new Rgba64((ushort)((uint)dstAt.R * {p}a1 / 0xffff + {p}r), (ushort)((uint)dstAt.G * {p}a1 / 0xffff + {p}g), (ushort)((uint)dstAt.B * {p}a1 / 0xffff + {p}b), (ushort)((uint)dstAt.A * {p}a1 / 0xffff + {p}a));\n");
                            sb.Append(Ind1).Append($"dst.{setter}({x}, {y}, dstColorRGBA64);\n");
                            sb.Append(ind).Append("}\n");
                            sb.Append(ind).Append("else\n").Append(ind).Append("{\n");
                            sb.Append(Ind1).Append($"dstColorRGBA64 = new Rgba64((ushort){p}r, (ushort){p}g, (ushort){p}b, (ushort){p}a);\n");
                            sb.Append(Ind1).Append($"dst.{setter}({x}, {y}, dstColorRGBA64);\n");
                            sb.Append(ind).Append("}\n");
                            sb.Length -= 1;
                        }
                        break;
                    case "Rgba":
                        switch (d.SType)
                        {
                            default:
                                for (int i = 0; i < 4; i++)
                                {
                                    string ch = "rgba"[i].ToString();
                                    sb.Append(ind).Append($"dst.Pix.Span[d + {i}] = (byte)({p}{ch} >> 8);\n");
                                }
                                sb.Length -= 1;
                                break;
                            case "Gray":
                                sb.Append(ind).Append($"byte Out = (byte)({p}r >> 8);\n");
                                for (int i = 0; i < 3; i++)
                                {
                                    sb.Append(ind).Append($"dst.Pix.Span[d + {i}] = Out;\n");
                                }
                                sb.Append(ind).Append($"dst.Pix.Span[d + 3] = 0xff;");
                                break;
                            case "YCbCr":
                                for (int i = 0; i < 3; i++)
                                {
                                    string ch = "rgb"[i].ToString();
                                    sb.Append(ind).Append($"dst.Pix.Span[d + {i}] = (byte)({p}{ch} >> 8);\n");
                                }
                                sb.Append(ind).Append($"dst.Pix.Span[d + 3] = 0xff;");
                                break;
                            case "Rgba64":
                                for (int i = 0; i < 4; i++)
                                {
                                    string ch = "RGBA"[i].ToString();
                                    sb.Append(ind).Append($"dst.Pix.Span[d + {i}] = (byte)({p}.{ch} >> 8);\n");
                                }
                                sb.Length -= 1;
                                break;
                        }
                        break;
                }
                break;
        }

        return sb.ToString().TrimEnd('\n');
    }

    private static string OutputF(GenData d, string suffix, string ind)
    {
        var (args, _) = SplitArgs(suffix);
        if (args == null || args.Length != 5)
        {
            return "";
        }
        string x = args[0], y = args[1], conv = args[2], p = args[3], w = args[4];
        string convFn = conv switch { "ftou" => "ScaleImpl.Ftou", "fffftou" => "ScaleImpl.Fffftou", _ => throw new Exception($"bad conv {conv}") };
        string W = w == "1" ? "" : $" * {w}";
        string Ind1 = ind + Sp(4);

        string ConvLines4(string prefix, string p0suffix) =>
            ind + $"{prefix}r0 = {convFn}({p}r{W}){p0suffix}\n" +
            ind + $"{prefix}g0 = {convFn}({p}g{W}){p0suffix}\n" +
            ind + $"{prefix}b0 = {convFn}({p}b{W}){p0suffix}\n" +
            ind + $"{prefix}a0 = {convFn}({p}a{W}){p0suffix}";

        var sb = new StringBuilder();

        switch (d.Op)
        {
            default:
                throw new Exception($"bad op {d.Op}");
            case "Over":
                switch (d.DType)
                {
                    default:
                        throw new Exception($"bad dType {d.DType}");
                    case "Image":
                        sb.Append(ind).Append($"(uint qr, uint qg, uint qb, uint qa) = dst.At({x}, {y}).Rgba();\n");
                        sb.Append(ConvLines4("uint " + p, ";"));
                        sb.Append('\n');
                        sb.Append(ind).Append("if (dstMask != null)\n").Append(ind).Append("{\n");
                        sb.Append(Ind1).Append($"(_, _, _, uint ma) = dstMask.At(dmp.X + {x}, dmp.Y + {y}).Rgba();\n");
                        sb.Append(Ind1).Append($"{p}r0 = {p}r0 * ma / 0xffff;\n");
                        sb.Append(Ind1).Append($"{p}g0 = {p}g0 * ma / 0xffff;\n");
                        sb.Append(Ind1).Append($"{p}b0 = {p}b0 * ma / 0xffff;\n");
                        sb.Append(Ind1).Append($"{p}a0 = {p}a0 * ma / 0xffff;\n");
                        sb.Append(ind).Append("}\n");
                        sb.Append(ind).Append($"uint {p}a1 = 0xffff - {p}a0;\n");
                        sb.Append(ind).Append($"dstColorRGBA64 = new Rgba64((ushort)(qr * {p}a1 / 0xffff + {p}r0), (ushort)(qg * {p}a1 / 0xffff + {p}g0), (ushort)(qb * {p}a1 / 0xffff + {p}b0), (ushort)(qa * {p}a1 / 0xffff + {p}a0));\n");
                        sb.Append(ind).Append($"dst.Set({x}, {y}, dstColorRGBA64);");
                        break;
                    case "Rgba64":
                        sb.Append(ind).Append($"Rgba64 dstAt = dst.Rgba64At({x}, {y});\n");
                        sb.Append(ConvLines4("uint " + p, ";"));
                        sb.Append('\n');
                        sb.Append(ind).Append("if (dstMask != null)\n").Append(ind).Append("{\n");
                        sb.Append(Ind1).Append($"(_, _, _, uint ma) = dstMask.At(dmp.X + {x}, dmp.Y + {y}).Rgba();\n");
                        sb.Append(Ind1).Append($"{p}r0 = {p}r0 * ma / 0xffff;\n");
                        sb.Append(Ind1).Append($"{p}g0 = {p}g0 * ma / 0xffff;\n");
                        sb.Append(Ind1).Append($"{p}b0 = {p}b0 * ma / 0xffff;\n");
                        sb.Append(Ind1).Append($"{p}a0 = {p}a0 * ma / 0xffff;\n");
                        sb.Append(ind).Append("}\n");
                        sb.Append(ind).Append($"uint {p}a1 = 0xffff - {p}a0;\n");
                        sb.Append(ind).Append($"dstColorRGBA64 = new Rgba64((ushort)((uint)dstAt.R * {p}a1 / 0xffff + {p}r0), (ushort)((uint)dstAt.G * {p}a1 / 0xffff + {p}g0), (ushort)((uint)dstAt.B * {p}a1 / 0xffff + {p}b0), (ushort)((uint)dstAt.A * {p}a1 / 0xffff + {p}a0));\n");
                        sb.Append(ind).Append($"dst.SetRgba64({x}, {y}, dstColorRGBA64);");
                        break;
                    case "Rgba":
                        sb.Append(ConvLines4("uint " + p, ";"));
                        sb.Append('\n');
                        sb.Append(ind).Append($"uint {p}a1 = (0xffff - {p}a0) * 0x101;\n");
                        for (int i = 0; i < 4; i++)
                        {
                            string ch = "rgba"[i].ToString();
                            sb.Append(ind).Append($"dst.Pix.Span[d + {i}] = (byte)(((uint)dst.Pix.Span[d + {i}] * {p}a1 / 0xffff + {p}{ch}0) >> 8);\n");
                        }
                        sb.Length -= 1;
                        break;
                }
                break;

            case "Src":
                switch (d.DType)
                {
                    default:
                        throw new Exception($"bad dType {d.DType}");
                    case "Image":
                        sb.Append(ind).Append("if (dstMask != null)\n").Append(ind).Append("{\n");
                        sb.Append(Ind1).Append($"(uint qr, uint qg, uint qb, uint qa) = dst.At({x}, {y}).Rgba();\n");
                        sb.Append(Ind1).Append($"(_, _, _, uint ma) = dstMask.At(dmp.X + {x}, dmp.Y + {y}).Rgba();\n");
                        sb.Append(Ind1).Append($"uint {p}r0 = {convFn}({p}r{W}) * ma / 0xffff;\n");
                        sb.Append(Ind1).Append($"uint {p}g0 = {convFn}({p}g{W}) * ma / 0xffff;\n");
                        sb.Append(Ind1).Append($"uint {p}b0 = {convFn}({p}b{W}) * ma / 0xffff;\n");
                        sb.Append(Ind1).Append($"uint {p}a0 = {convFn}({p}a{W}) * ma / 0xffff;\n");
                        sb.Append(Ind1).Append($"uint {p}a1 = 0xffff - ma;\n");
                        sb.Append(Ind1).Append($"dstColorRGBA64 = new Rgba64((ushort)(qr * {p}a1 / 0xffff + {p}r0), (ushort)(qg * {p}a1 / 0xffff + {p}g0), (ushort)(qb * {p}a1 / 0xffff + {p}b0), (ushort)(qa * {p}a1 / 0xffff + {p}a0));\n");
                        sb.Append(Ind1).Append($"dst.Set({x}, {y}, dstColorRGBA64);\n");
                        sb.Append(ind).Append("}\n");
                        sb.Append(ind).Append("else\n").Append(ind).Append("{\n");
                        sb.Append(Ind1).Append($"dstColorRGBA64 = new Rgba64({convFn}({p}r{W}), {convFn}({p}g{W}), {convFn}({p}b{W}), {convFn}({p}a{W}));\n");
                        sb.Append(Ind1).Append($"dst.Set({x}, {y}, dstColorRGBA64);\n");
                        sb.Append(ind).Append("}\n");
                        sb.Length -= 1;
                        break;
                    case "Rgba64":
                        sb.Append(ind).Append("if (dstMask != null)\n").Append(ind).Append("{\n");
                        sb.Append(Ind1).Append($"Rgba64 dstAt = dst.Rgba64At({x}, {y});\n");
                        sb.Append(Ind1).Append($"(_, _, _, uint ma) = dstMask.At(dmp.X + {x}, dmp.Y + {y}).Rgba();\n");
                        sb.Append(Ind1).Append($"uint {p}r0 = {convFn}({p}r{W}) * ma / 0xffff;\n");
                        sb.Append(Ind1).Append($"uint {p}g0 = {convFn}({p}g{W}) * ma / 0xffff;\n");
                        sb.Append(Ind1).Append($"uint {p}b0 = {convFn}({p}b{W}) * ma / 0xffff;\n");
                        sb.Append(Ind1).Append($"uint {p}a0 = {convFn}({p}a{W}) * ma / 0xffff;\n");
                        sb.Append(Ind1).Append($"uint {p}a1 = 0xffff - ma;\n");
                        sb.Append(Ind1).Append($"dstColorRGBA64 = new Rgba64((ushort)((uint)dstAt.R * {p}a1 / 0xffff + {p}r0), (ushort)((uint)dstAt.G * {p}a1 / 0xffff + {p}g0), (ushort)((uint)dstAt.B * {p}a1 / 0xffff + {p}b0), (ushort)((uint)dstAt.A * {p}a1 / 0xffff + {p}a0));\n");
                        sb.Append(Ind1).Append($"dst.SetRgba64({x}, {y}, dstColorRGBA64);\n");
                        sb.Append(ind).Append("}\n");
                        sb.Append(ind).Append("else\n").Append(ind).Append("{\n");
                        sb.Append(Ind1).Append($"dstColorRGBA64 = new Rgba64({convFn}({p}r{W}), {convFn}({p}g{W}), {convFn}({p}b{W}), {convFn}({p}a{W}));\n");
                        sb.Append(Ind1).Append($"dst.SetRgba64({x}, {y}, dstColorRGBA64);\n");
                        sb.Append(ind).Append("}\n");
                        sb.Length -= 1;
                        break;
                    case "Rgba":
                        switch (d.SType)
                        {
                            default:
                                for (int i = 0; i < 4; i++)
                                {
                                    string ch = "rgba"[i].ToString();
                                    sb.Append(ind).Append($"dst.Pix.Span[d + {i}] = (byte)({convFn}({p}{ch}{W}) >> 8);\n");
                                }
                                sb.Length -= 1;
                                break;
                            case "Gray":
                                sb.Append(ind).Append($"byte Out = (byte)({convFn}({p}r{W}) >> 8);\n");
                                for (int i = 0; i < 3; i++)
                                {
                                    sb.Append(ind).Append($"dst.Pix.Span[d + {i}] = Out;\n");
                                }
                                sb.Append(ind).Append($"dst.Pix.Span[d + 3] = 0xff;");
                                break;
                            case "YCbCr":
                                for (int i = 0; i < 3; i++)
                                {
                                    string ch = "rgb"[i].ToString();
                                    sb.Append(ind).Append($"dst.Pix.Span[d + {i}] = (byte)({convFn}({p}{ch}{W}) >> 8);\n");
                                }
                                sb.Append(ind).Append($"dst.Pix.Span[d + 3] = 0xff;");
                                break;
                        }
                        break;
                }
                break;
        }

        return sb.ToString().TrimEnd('\n');
    }

    private static string TmpOut(GenData d, string ind)
    {
        switch (d.SType)
        {
            case "Gray":
                return ind + "tmp[t4 + 0] = pr;\n" + ind + "tmp[t4 + 1] = pr;\n" + ind + "tmp[t4 + 2] = pr;\n" + ind + "tmp[t4 + 3] = 1.0;";
            case "YCbCr":
                return ind + "tmp[t4 + 0] = pr * b.InvTotalWeightFFFF;\n" + ind + "tmp[t4 + 1] = pg * b.InvTotalWeightFFFF;\n" + ind + "tmp[t4 + 2] = pb * b.InvTotalWeightFFFF;\n" + ind + "tmp[t4 + 3] = 1.0;";
            default:
                return ind + "tmp[t4 + 0] = pr * b.InvTotalWeightFFFF;\n" + ind + "tmp[t4 + 1] = pg * b.InvTotalWeightFFFF;\n" + ind + "tmp[t4 + 2] = pb * b.InvTotalWeightFFFF;\n" + ind + "tmp[t4 + 3] = pa * b.InvTotalWeightFFFF;";
        }
    }
}